import { cva } from "class-variance-authority";

export const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground shadow-xs hover:bg-primary/90",
        destructive:
          "bg-destructive text-white shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
        outline:
          "border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
        secondary: "bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
        link: "text-primary underline-offset-4 hover:underline",
        toolbar: "text-secondary hover:bg-surface hover:text-primary",
        surface: "bg-surface text-secondary hover:bg-elevated hover:text-primary",
        subtle: "text-muted hover:bg-white/10 hover:text-primary",
        inline: "text-muted hover:text-secondary",
        danger: "text-muted hover:bg-destructive/10 hover:text-destructive",
        navigation: "project-item group w-full justify-start rounded-lg text-left text-primary",
        issue: "issue-row w-full justify-start rounded-none border-b border-border text-left hover:bg-surface/50",
        panel: "w-full rounded-none justify-between hover:bg-surface/50",
        status: "rounded-lg font-medium",
        tab: "rounded-none border-b-2 border-transparent text-muted hover:text-secondary",
        segment: "rounded-[calc(var(--radius-md)-2px)] text-secondary hover:text-primary",
        dependency: "w-full justify-start rounded bg-surface text-left hover:bg-elevated",
        blockedDependency: "w-full justify-start rounded bg-red-500/10 text-left hover:bg-red-500/20",
      },
      size: {
        default: "h-9 px-4 py-2 has-[>svg]:px-3",
        xs: "h-7 rounded px-2 text-xs has-[>svg]:px-2",
        sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",
        lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
        icon: "size-9",
        "icon-xs": "size-6 rounded",
        "icon-sm": "size-8",
        "icon-lg": "size-10",
        toolbar: "size-7 rounded-md",
        nav: "px-3 py-2",
        "nav-lg": "px-3 py-2.5",
        compact: "px-4 py-2.5",
        comfortable: "px-4 py-3",
        panel: "p-3",
        tab: "px-3 py-2 text-xs",
        dependency: "px-2 py-1.5",
      },
      isActive: {
        true: "",
        false: "",
      },
      tone: {
        default: "",
        accent: "",
        ready: "",
        overdue: "",
        blocked: "",
        pinned: "",
        open: "",
        progress: "",
        closed: "",
        deferred: "",
      },
    },
    compoundVariants: [
      { variant: "navigation", isActive: true, className: "active" },
      { variant: "segment", isActive: true, className: "bg-elevated text-primary shadow-xs" },
      { variant: "tab", isActive: true, tone: "default", className: "border-accent text-accent" },
      { variant: "tab", isActive: true, tone: "accent", className: "border-accent text-accent" },
      { variant: "tab", isActive: true, tone: "ready", className: "border-green-500 text-green-500" },
      { variant: "tab", isActive: true, tone: "overdue", className: "border-red-500 text-red-500" },
      { variant: "tab", isActive: true, tone: "blocked", className: "border-red-400 text-red-400" },
      { variant: "toolbar", isActive: true, tone: "pinned", className: "bg-accent/20 text-accent" },
      { variant: "issue", isActive: true, className: "border-l-2 border-l-accent bg-accent/10" },
      { variant: "status", tone: "open", className: "bg-[var(--color-status-open)]/10 text-[var(--color-status-open)]" },
      {
        variant: "status",
        tone: "progress",
        className: "bg-[var(--color-status-progress)]/10 text-[var(--color-status-progress)]",
      },
      { variant: "status", tone: "closed", className: "bg-[var(--color-status-closed)]/10 text-[var(--color-status-closed)]" },
      { variant: "status", tone: "blocked", className: "bg-red-500/10 text-red-500" },
      { variant: "status", tone: "deferred", className: "bg-gray-500/10 text-gray-500" },
    ],
    defaultVariants: {
      variant: "default",
      size: "default",
      isActive: false,
      tone: "default",
    },
  },
);
